### ISSUE TITLE
Host Delete is not working

### ISSUE THREAD

**Issue by YasinUzn** [rbltracker/rbltracker-php#2]
Seems like host->delete is not working as expected. 

Steps to reproduce:

test.php
```
<?php

require 'vendor/autoload.php';

use RBLTracker\Client;

$client = new Client('your_account_sid', 'your_auth_token');
$deleteHost = $client->host->delete('yourhostidtodelete');
print_r($deleteHost);
```

Error:
```
PHP Fatal error:  Uncaught RBLTracker\Exceptions\RBLTrackerException: failed to decode response from RBLTracker API in /../vendor/rbltracker/sdk/RBLTracker/API/RequestHandler.php:167
Stack trace:
0 /../vendor/rbltracker/sdk/RBLTracker/API/RequestHandler.php(193): RBLTracker\API\Host->request('POST', 'host/delete/HT9...', NULL)
1 /../vendor/rbltracker/sdk/RBLTracker/API/Host.php(55): RBLTracker\API\Host->_post('host/delete/HT9...')
```

Am I missing something here? 

Thanks in advance.

**Comment by mikepultz** [comment]
Hey @YasinUzn,

I haven't been able to reproduce this error; can you confirm you're running the latest version of the SDK? (v1.0.3)

The error references RequestHandler.php:167 - but there's nothing on that line that would cause an issue- so i think you must be running an older version.

Let me know,

Mike

**Comment by YasinUzn** [comment]
Hi @mikepultz,

Sorry for late response. I can verify that issue persist on version 1.0.3

I had some time to debug the issue seems like problem happens on RequestHandler line 63  :

```
                curl_setopt($c, CURLOPT_HTTPHEADER, [
                    'Content-type' => 'application/x-www-form-urlencoded',
                ])
```
                
As I see it this sets 'Content-Length: -1' on delete endpoint request, which causes to fail. 

If I  manually update that into this:

```
                curl_setopt($c, CURLOPT_HTTPHEADER, [
                    'Content-Length: 0',
                    'Content-type: application/x-www-form-urlencoded',
                ]);
```
                
Delete request will work as expected. I am suspecting this might has something to do with curl version because you can not reproduce.

My curl version is:
 
 ```
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
 
```

Hope it helps.

**Comment by mikepultz** [comment]
Hey @YasinUzn,

So I tried a few different versions of CURL, but I still wasn't able to reproduce.

But I've included a fix that sets the content-length to 0 (like in your example) in the event there's no data; if this resolves this issue, there's no harm in adding it.

I've pushed an updated release with a few other changes,

Mike
